class EmojiOption {
  const EmojiOption({
    required this.emoji,
    required this.label,
    required this.keywords,
    required this.category,
  });

  final String emoji;
  final String label;
  final List<String> keywords;
  final String category;
}

abstract final class HabitEmojiCategories {
  static const String recent = 'recent';
  static const String frequent = 'frequent';
  static const String health = 'health';
  static const String sport = 'sport';
  static const String mind = 'mind';
  static const String study = 'study';
  static const String work = 'work';
  static const String sleep = 'sleep';
  static const String food = 'food';
  static const String home = 'home';
  static const String social = 'social';
  static const String creativity = 'creativity';
  static const String finance = 'finance';
  static const String nature = 'nature';
  static const String spirituality = 'spirituality';
  static const String leisure = 'leisure';
  static const String others = 'others';
}

const List<String> kHabitEmojiCategoryOrder = <String>[
  HabitEmojiCategories.recent,
  HabitEmojiCategories.frequent,
  HabitEmojiCategories.health,
  HabitEmojiCategories.sport,
  HabitEmojiCategories.mind,
  HabitEmojiCategories.study,
  HabitEmojiCategories.work,
  HabitEmojiCategories.sleep,
  HabitEmojiCategories.food,
  HabitEmojiCategories.home,
  HabitEmojiCategories.social,
  HabitEmojiCategories.creativity,
  HabitEmojiCategories.finance,
  HabitEmojiCategories.nature,
  HabitEmojiCategories.spirituality,
  HabitEmojiCategories.leisure,
  HabitEmojiCategories.others,
];

const List<EmojiOption> kHabitEmojiOptions = <EmojiOption>[
  EmojiOption(
    emoji: '📖',
    label: 'Leer',
    keywords: <String>[
      'leer',
      'lectura',
      'libro',
      'read',
      'reading',
      'book',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '📚',
    label: 'Libros',
    keywords: <String>[
      'libros',
      'biblioteca',
      'estudiar',
      'study',
      'books',
      'reading',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '💧',
    label: 'Agua',
    keywords: <String>[
      'agua',
      'beber',
      'hidratar',
      'hidratarse',
      'hidratacion',
      'water',
      'drink',
      'hydrate',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🏃',
    label: 'Correr',
    keywords: <String>[
      'correr',
      'carrera',
      'run',
      'running',
      'cardio',
      'trotar',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🚶',
    label: 'Caminar',
    keywords: <String>[
      'caminar',
      'pasos',
      'andar',
      'walk',
      'walking',
      'steps',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🧘',
    label: 'Meditar',
    keywords: <String>[
      'meditar',
      'meditacion',
      'calma',
      'mindful',
      'meditate',
      'breathing',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '😴',
    label: 'Dormir',
    keywords: <String>[
      'dormir',
      'sueno',
      'descanso',
      'siesta',
      'sleep',
      'rest',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🏋️',
    label: 'Entrenar',
    keywords: <String>[
      'entrenar',
      'entrenamiento',
      'gimnasio',
      'gym',
      'workout',
      'strength',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '✍️',
    label: 'Escribir',
    keywords: <String>[
      'escribir',
      'escritura',
      'write',
      'writing',
      'texto',
      'draft',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '📝',
    label: 'Journal',
    keywords: <String>[
      'diario',
      'journal',
      'journaling',
      'nota',
      'notas',
      'reflexion',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '☕',
    label: 'Cafe',
    keywords: <String>[
      'cafe',
      'coffee',
      'cafeteria',
      'espresso',
      'latte',
      'morning',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🍎',
    label: 'Fruta',
    keywords: <String>[
      'fruta',
      'comida',
      'food',
      'healthy',
      'snack',
      'manzana',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🧹',
    label: 'Limpiar',
    keywords: <String>[
      'limpiar',
      'limpieza',
      'clean',
      'cleaning',
      'orden',
      'ordenar',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '💼',
    label: 'Trabajo',
    keywords: <String>[
      'trabajo',
      'work',
      'office',
      'productividad',
      'job',
      'laboral',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🎵',
    label: 'Musica',
    keywords: <String>[
      'musica',
      'music',
      'song',
      'escuchar',
      'playlist',
      'audio',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '❤️',
    label: 'Amor propio',
    keywords: <String>[
      'amor',
      'self care',
      'cuidado',
      'heart',
      'quererme',
      'wellbeing',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '✅',
    label: 'Completar',
    keywords: <String>[
      'completar',
      'tarea',
      'tareas',
      'done',
      'check',
      'checklist',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🔥',
    label: 'Racha',
    keywords: <String>[
      'racha',
      'streak',
      'disciplina',
      'motivacion',
      'consistencia',
      'habit',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🎯',
    label: 'Objetivo',
    keywords: <String>[
      'objetivo',
      'meta',
      'goal',
      'focus',
      'foco',
      'target',
    ],
    category: HabitEmojiCategories.frequent,
  ),
  EmojiOption(
    emoji: '🩺',
    label: 'Salud',
    keywords: <String>[
      'salud',
      'health',
      'doctor',
      'medico',
      'checkup',
      'wellness',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '💊',
    label: 'Medicina',
    keywords: <String>[
      'medicina',
      'medicacion',
      'medicine',
      'pill',
      'pastilla',
      'doctor',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🦷',
    label: 'Dental',
    keywords: <String>[
      'dental',
      'dientes',
      'dentista',
      'teeth',
      'tooth',
      'mouth',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🧴',
    label: 'Skincare',
    keywords: <String>[
      'skincare',
      'piel',
      'skin',
      'cara',
      'crema',
      'rutina facial',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🧼',
    label: 'Higiene',
    keywords: <String>[
      'higiene',
      'soap',
      'lavarse',
      'clean',
      'body care',
      'aseo',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🛁',
    label: 'Bano',
    keywords: <String>[
      'bano',
      'ducha',
      'bath',
      'shower',
      'relax',
      'higiene',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🥗',
    label: 'Ensalada',
    keywords: <String>[
      'ensalada',
      'vegetales',
      'salad',
      'healthy food',
      'comida sana',
      'greens',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🥛',
    label: 'Leche',
    keywords: <String>[
      'leche',
      'milk',
      'proteina',
      'desayuno',
      'drink',
      'nutricion',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🫁',
    label: 'Respirar',
    keywords: <String>[
      'respirar',
      'respiracion',
      'breath',
      'breathing',
      'oxigeno',
      'lung',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🧠',
    label: 'Mente',
    keywords: <String>[
      'mente',
      'brain',
      'mental',
      'focus',
      'foco',
      'claridad',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🦵',
    label: 'Piernas',
    keywords: <String>[
      'pierna',
      'piernas',
      'leg',
      'legs',
      'movilidad',
      'strength',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '💪',
    label: 'Fuerza',
    keywords: <String>[
      'fuerza',
      'strength',
      'musculo',
      'gym',
      'workout',
      'arm',
    ],
    category: HabitEmojiCategories.health,
  ),
  EmojiOption(
    emoji: '🚴',
    label: 'Bicicleta',
    keywords: <String>[
      'bici',
      'bicicleta',
      'bike',
      'cycling',
      'cardio',
      'pedalear',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🏊',
    label: 'Nadar',
    keywords: <String>[
      'nadar',
      'natacion',
      'swim',
      'swimming',
      'piscina',
      'pool',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '⚽',
    label: 'Futbol',
    keywords: <String>[
      'futbol',
      'soccer',
      'ball',
      'deporte',
      'team',
      'practice',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🏀',
    label: 'Baloncesto',
    keywords: <String>[
      'baloncesto',
      'basket',
      'basketball',
      'canasta',
      'deporte',
      'entrenar',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🎾',
    label: 'Tenis',
    keywords: <String>[
      'tenis',
      'tennis',
      'raqueta',
      'deporte',
      'court',
      'practice',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🥊',
    label: 'Boxeo',
    keywords: <String>[
      'boxeo',
      'boxing',
      'fight',
      'sparring',
      'guantes',
      'training',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🧗',
    label: 'Escalar',
    keywords: <String>[
      'escalar',
      'climb',
      'climbing',
      'montana',
      'wall',
      'challenge',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🤸',
    label: 'Movilidad',
    keywords: <String>[
      'movilidad',
      'estirar',
      'stretch',
      'gymnastics',
      'flexibilidad',
      'warmup',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🛹',
    label: 'Skate',
    keywords: <String>[
      'skate',
      'patinar',
      'skateboard',
      'board',
      'ocio activo',
      'ride',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🏓',
    label: 'Ping pong',
    keywords: <String>[
      'ping pong',
      'tenis de mesa',
      'table tennis',
      'paleta',
      'juego',
      'deporte',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '🏹',
    label: 'Tiro con arco',
    keywords: <String>[
      'arco',
      'archery',
      'precision',
      'focus',
      'deporte',
      'target',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '⛹️',
    label: 'Practicar deporte',
    keywords: <String>[
      'deporte',
      'sport',
      'practice',
      'entrenar',
      'actividad',
      'move',
    ],
    category: HabitEmojiCategories.sport,
  ),
  EmojiOption(
    emoji: '⏱️',
    label: 'Tiempo',
    keywords: <String>[
      'tiempo',
      'timer',
      'time',
      'pomodoro',
      'focus',
      'productividad',
    ],
    category: HabitEmojiCategories.mind,
  ),
  EmojiOption(
    emoji: '⌛',
    label: 'Paciencia',
    keywords: <String>[
      'paciencia',
      'esperar',
      'wait',
      'slow',
      'mindful',
      'restraint',
    ],
    category: HabitEmojiCategories.mind,
  ),
  EmojiOption(
    emoji: '📌',
    label: 'Prioridad',
    keywords: <String>[
      'prioridad',
      'recordar',
      'pin',
      'important',
      'focus',
      'top task',
    ],
    category: HabitEmojiCategories.mind,
  ),
  EmojiOption(
    emoji: '🌱',
    label: 'Crecer',
    keywords: <String>[
      'crecer',
      'growth',
      'mejorar',
      'mindset',
      'habit',
      'progress',
    ],
    category: HabitEmojiCategories.mind,
  ),
  EmojiOption(
    emoji: '🔕',
    label: 'Sin distracciones',
    keywords: <String>[
      'silencio',
      'sin distracciones',
      'notifications off',
      'focus',
      'deep work',
      'mute',
    ],
    category: HabitEmojiCategories.mind,
  ),
  EmojiOption(
    emoji: '🧩',
    label: 'Resolver',
    keywords: <String>[
      'resolver',
      'problema',
      'puzzle',
      'pensar',
      'logic',
      'brain',
    ],
    category: HabitEmojiCategories.mind,
  ),
  EmojiOption(
    emoji: '💭',
    label: 'Reflexionar',
    keywords: <String>[
      'reflexionar',
      'pensar',
      'thought',
      'journal',
      'mind',
      'idea',
    ],
    category: HabitEmojiCategories.mind,
  ),
  EmojiOption(
    emoji: '🕯️',
    label: 'Calma',
    keywords: <String>[
      'calma',
      'calm',
      'quiet',
      'pausa',
      'mindful',
      'serenidad',
    ],
    category: HabitEmojiCategories.mind,
  ),
  EmojiOption(
    emoji: '📓',
    label: 'Cuaderno',
    keywords: <String>[
      'cuaderno',
      'notebook',
      'diario',
      'study',
      'journal',
      'apuntes',
    ],
    category: HabitEmojiCategories.study,
  ),
  EmojiOption(
    emoji: '📔',
    label: 'Apuntes',
    keywords: <String>[
      'apuntes',
      'notas',
      'notes',
      'clase',
      'study',
      'repasar',
    ],
    category: HabitEmojiCategories.study,
  ),
  EmojiOption(
    emoji: '📒',
    label: 'Estudio',
    keywords: <String>[
      'estudio',
      'estudiar',
      'study',
      'learning',
      'aprender',
      'exam',
    ],
    category: HabitEmojiCategories.study,
  ),
  EmojiOption(
    emoji: '🖊️',
    label: 'Boligrafo',
    keywords: <String>[
      'boligrafo',
      'pen',
      'write',
      'writing',
      'notas',
      'study',
    ],
    category: HabitEmojiCategories.study,
  ),
  EmojiOption(
    emoji: '✏️',
    label: 'Lapiz',
    keywords: <String>[
      'lapiz',
      'pencil',
      'escribir',
      'apuntar',
      'draw',
      'homework',
    ],
    category: HabitEmojiCategories.study,
  ),
  EmojiOption(
    emoji: '💻',
    label: 'Portatil',
    keywords: <String>[
      'portatil',
      'laptop',
      'computer',
      'study',
      'online',
      'curso',
    ],
    category: HabitEmojiCategories.study,
  ),
  EmojiOption(
    emoji: '🎧',
    label: 'Escuchar clase',
    keywords: <String>[
      'audio',
      'listen',
      'lecture',
      'estudiar',
      'podcast',
      'music',
    ],
    category: HabitEmojiCategories.study,
  ),
  EmojiOption(
    emoji: '🗓️',
    label: 'Plan de estudio',
    keywords: <String>[
      'calendario',
      'calendar',
      'planificar',
      'study plan',
      'agenda',
      'schedule',
    ],
    category: HabitEmojiCategories.study,
  ),
  EmojiOption(
    emoji: '📊',
    label: 'Analizar',
    keywords: <String>[
      'analizar',
      'datos',
      'analytics',
      'chart',
      'work',
      'productividad',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '📈',
    label: 'Progreso',
    keywords: <String>[
      'progreso',
      'growth',
      'metrics',
      'chart',
      'work',
      'business',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '📉',
    label: 'Revisar',
    keywords: <String>[
      'revisar',
      'review',
      'report',
      'metrics',
      'work',
      'analysis',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '📅',
    label: 'Calendario',
    keywords: <String>[
      'calendario',
      'calendar',
      'agenda',
      'schedule',
      'meeting',
      'planificar',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '📧',
    label: 'Email',
    keywords: <String>[
      'email',
      'correo',
      'mail',
      'inbox',
      'work',
      'reply',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '📞',
    label: 'Llamada',
    keywords: <String>[
      'llamada',
      'llamar',
      'call',
      'telefono',
      'work',
      'contact',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '🗂️',
    label: 'Organizar',
    keywords: <String>[
      'organizar',
      'orden',
      'folders',
      'documents',
      'tidy',
      'workspace',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '🗒️',
    label: 'Agenda',
    keywords: <String>[
      'agenda',
      'planning',
      'schedule',
      'meeting',
      'calendar',
      'workday',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '🖥️',
    label: 'Escritorio',
    keywords: <String>[
      'escritorio',
      'desktop',
      'computer',
      'trabajo',
      'office',
      'workspace',
    ],
    category: HabitEmojiCategories.work,
  ),
  EmojiOption(
    emoji: '💤',
    label: 'Descansar',
    keywords: <String>[
      'descansar',
      'descanso',
      'rest',
      'sleep',
      'recover',
      'relax',
    ],
    category: HabitEmojiCategories.sleep,
  ),
  EmojiOption(
    emoji: '🛏️',
    label: 'Cama',
    keywords: <String>[
      'cama',
      'bed',
      'sleep',
      'dormir',
      'siesta',
      'night',
    ],
    category: HabitEmojiCategories.sleep,
  ),
  EmojiOption(
    emoji: '🌙',
    label: 'Noche',
    keywords: <String>[
      'noche',
      'night',
      'sleep',
      'luna',
      'moon',
      'rest',
    ],
    category: HabitEmojiCategories.sleep,
  ),
  EmojiOption(
    emoji: '🌌',
    label: 'Dormir temprano',
    keywords: <String>[
      'dormir temprano',
      'deep sleep',
      'night sky',
      'sueno',
      'sleep',
      'stars',
    ],
    category: HabitEmojiCategories.sleep,
  ),
  EmojiOption(
    emoji: '🛌',
    label: 'Ir a la cama',
    keywords: <String>[
      'ir a la cama',
      'sleep routine',
      'bedtime',
      'dormir',
      'night',
      'rest',
    ],
    category: HabitEmojiCategories.sleep,
  ),
  EmojiOption(
    emoji: '🧦',
    label: 'Comodidad',
    keywords: <String>[
      'comodidad',
      'comfort',
      'warm',
      'relax',
      'home',
      'rest',
    ],
    category: HabitEmojiCategories.sleep,
  ),
  EmojiOption(
    emoji: '🧸',
    label: 'Descanso suave',
    keywords: <String>[
      'descanso',
      'soft',
      'relax',
      'sleep',
      'calma',
      'comfort',
    ],
    category: HabitEmojiCategories.sleep,
  ),
  EmojiOption(
    emoji: '🫖',
    label: 'Te',
    keywords: <String>[
      'te',
      'tea',
      'infusion',
      'drink',
      'warm drink',
      'relax',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🥤',
    label: 'Bebida',
    keywords: <String>[
      'bebida',
      'drink',
      'smoothie',
      'batido',
      'tomar',
      'hydration',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🍌',
    label: 'Platano',
    keywords: <String>[
      'platano',
      'banana',
      'fruta',
      'snack',
      'food',
      'eat',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🥑',
    label: 'Aguacate',
    keywords: <String>[
      'aguacate',
      'avocado',
      'healthy',
      'food',
      'comida',
      'breakfast',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🍳',
    label: 'Cocinar',
    keywords: <String>[
      'cocinar',
      'cook',
      'cooking',
      'desayuno',
      'food',
      'meal prep',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🍚',
    label: 'Arroz',
    keywords: <String>[
      'arroz',
      'rice',
      'meal',
      'comida',
      'lunch',
      'dinner',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🍞',
    label: 'Pan',
    keywords: <String>[
      'pan',
      'bread',
      'breakfast',
      'food',
      'snack',
      'comida',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🍣',
    label: 'Comida',
    keywords: <String>[
      'comida',
      'food',
      'meal',
      'cena',
      'almuerzo',
      'eat',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🍽️',
    label: 'Comer',
    keywords: <String>[
      'comer',
      'eating',
      'meal',
      'food',
      'plate',
      'cocina',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🥦',
    label: 'Verduras',
    keywords: <String>[
      'verduras',
      'brocoli',
      'vegetables',
      'healthy',
      'food',
      'greens',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🥕',
    label: 'Vegetales',
    keywords: <String>[
      'vegetales',
      'zanahoria',
      'carrot',
      'healthy',
      'food',
      'snack',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🍊',
    label: 'Citricos',
    keywords: <String>[
      'citricos',
      'naranja',
      'orange',
      'vitamina',
      'fruit',
      'fruta',
    ],
    category: HabitEmojiCategories.food,
  ),
  EmojiOption(
    emoji: '🧽',
    label: 'Fregar',
    keywords: <String>[
      'fregar',
      'esponja',
      'clean',
      'kitchen',
      'casa',
      'limpieza',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '🧺',
    label: 'Ropa',
    keywords: <String>[
      'ropa',
      'laundry',
      'lavar',
      'wash',
      'colada',
      'laundry basket',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '🛒',
    label: 'Compra',
    keywords: <String>[
      'compra',
      'comprar',
      'shopping',
      'groceries',
      'supermercado',
      'market',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '🪴',
    label: 'Casa',
    keywords: <String>[
      'casa',
      'hogar',
      'home',
      'plantas',
      'room',
      'interior',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '🧻',
    label: 'Reponer',
    keywords: <String>[
      'reponer',
      'bano',
      'bathroom',
      'papel',
      'home',
      'stock',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '🧯',
    label: 'Arreglar',
    keywords: <String>[
      'arreglar',
      'fix',
      'repair',
      'seguridad',
      'casa',
      'maintenance',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '🧰',
    label: 'Herramientas',
    keywords: <String>[
      'herramientas',
      'tools',
      'bricolaje',
      'fix',
      'home',
      'repair',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '🪟',
    label: 'Ventilar',
    keywords: <String>[
      'ventilar',
      'window',
      'abrir ventana',
      'casa',
      'aire',
      'home',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '🚪',
    label: 'Orden en casa',
    keywords: <String>[
      'orden',
      'home',
      'entryway',
      'casa',
      'organizar',
      'limpiar',
    ],
    category: HabitEmojiCategories.home,
  ),
  EmojiOption(
    emoji: '💬',
    label: 'Mensaje',
    keywords: <String>[
      'mensaje',
      'mensajes',
      'chat',
      'talk',
      'social',
      'friends',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '🤝',
    label: 'Conectar',
    keywords: <String>[
      'conectar',
      'friends',
      'network',
      'social',
      'amistad',
      'team',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '😊',
    label: 'Amistad',
    keywords: <String>[
      'amigos',
      'friend',
      'friends',
      'social',
      'sonreir',
      'bond',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '🙏',
    label: 'Gratitud',
    keywords: <String>[
      'gratitud',
      'grateful',
      'rezar',
      'agradecer',
      'thanks',
      'spirituality',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '🎁',
    label: 'Regalo',
    keywords: <String>[
      'regalo',
      'gift',
      'celebrar',
      'social',
      'family',
      'friends',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '👨‍👩‍👧‍👦',
    label: 'Familia',
    keywords: <String>[
      'familia',
      'family',
      'hogar',
      'casa',
      'parents',
      'kids',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '👫',
    label: 'Pareja',
    keywords: <String>[
      'pareja',
      'relationship',
      'partner',
      'amor',
      'social',
      'together',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '👥',
    label: 'Grupo',
    keywords: <String>[
      'grupo',
      'team',
      'people',
      'social',
      'comunidad',
      'friends',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '🥂',
    label: 'Celebrar',
    keywords: <String>[
      'celebrar',
      'celebration',
      'brindis',
      'social',
      'friends',
      'party',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '🎉',
    label: 'Fiesta',
    keywords: <String>[
      'fiesta',
      'party',
      'celebrar',
      'social',
      'cumpleanos',
      'fun',
    ],
    category: HabitEmojiCategories.social,
  ),
  EmojiOption(
    emoji: '🎨',
    label: 'Arte',
    keywords: <String>[
      'arte',
      'art',
      'paint',
      'creative',
      'dibujo',
      'pintar',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '📷',
    label: 'Foto',
    keywords: <String>[
      'foto',
      'fotografia',
      'photo',
      'camera',
      'creative',
      'shoot',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '🎥',
    label: 'Video',
    keywords: <String>[
      'video',
      'filmar',
      'film',
      'camera',
      'creative',
      'record',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '🎹',
    label: 'Piano',
    keywords: <String>[
      'piano',
      'music',
      'practice',
      'instrumento',
      'creative',
      'play',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '🎸',
    label: 'Guitarra',
    keywords: <String>[
      'guitarra',
      'guitar',
      'music',
      'practice',
      'instrumento',
      'creative',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '🖌️',
    label: 'Pintar',
    keywords: <String>[
      'pintar',
      'paint',
      'brush',
      'arte',
      'creative',
      'dibujo',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '🧶',
    label: 'Tejer',
    keywords: <String>[
      'tejer',
      'yarn',
      'craft',
      'manualidades',
      'creative',
      'knit',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '🎭',
    label: 'Teatro',
    keywords: <String>[
      'teatro',
      'acting',
      'performance',
      'creative',
      'art',
      'scene',
    ],
    category: HabitEmojiCategories.creativity,
  ),
  EmojiOption(
    emoji: '💰',
    label: 'Ahorrar',
    keywords: <String>[
      'ahorrar',
      'ahorro',
      'dinero',
      'money',
      'save',
      'savings',
    ],
    category: HabitEmojiCategories.finance,
  ),
  EmojiOption(
    emoji: '🪙',
    label: 'Monedas',
    keywords: <String>[
      'monedas',
      'coins',
      'dinero',
      'cash',
      'money',
      'finanzas',
    ],
    category: HabitEmojiCategories.finance,
  ),
  EmojiOption(
    emoji: '🏦',
    label: 'Banco',
    keywords: <String>[
      'banco',
      'bank',
      'finanzas',
      'savings',
      'money',
      'cuenta',
    ],
    category: HabitEmojiCategories.finance,
  ),
  EmojiOption(
    emoji: '💳',
    label: 'Tarjeta',
    keywords: <String>[
      'tarjeta',
      'card',
      'credito',
      'debito',
      'pagar',
      'finanzas',
    ],
    category: HabitEmojiCategories.finance,
  ),
  EmojiOption(
    emoji: '🧾',
    label: 'Gastos',
    keywords: <String>[
      'gastos',
      'receipt',
      'expenses',
      'budget',
      'finanzas',
      'pagar',
    ],
    category: HabitEmojiCategories.finance,
  ),
  EmojiOption(
    emoji: '💵',
    label: 'Presupuesto',
    keywords: <String>[
      'presupuesto',
      'budget',
      'cash',
      'money',
      'finanzas',
      'ahorro',
    ],
    category: HabitEmojiCategories.finance,
  ),
  EmojiOption(
    emoji: '🧮',
    label: 'Calcular',
    keywords: <String>[
      'calcular',
      'contabilidad',
      'calculator',
      'numbers',
      'finance',
      'math',
    ],
    category: HabitEmojiCategories.finance,
  ),
  EmojiOption(
    emoji: '🌿',
    label: 'Naturaleza',
    keywords: <String>[
      'naturaleza',
      'nature',
      'verde',
      'green',
      'outdoors',
      'calma',
    ],
    category: HabitEmojiCategories.nature,
  ),
  EmojiOption(
    emoji: '🌳',
    label: 'Arbol',
    keywords: <String>[
      'arbol',
      'tree',
      'bosque',
      'forest',
      'nature',
      'park',
    ],
    category: HabitEmojiCategories.nature,
  ),
  EmojiOption(
    emoji: '🌞',
    label: 'Sol',
    keywords: <String>[
      'sol',
      'sun',
      'morning',
      'outside',
      'nature',
      'light',
    ],
    category: HabitEmojiCategories.nature,
  ),
  EmojiOption(
    emoji: '🌊',
    label: 'Mar',
    keywords: <String>[
      'mar',
      'sea',
      'ocean',
      'agua',
      'beach',
      'nature',
    ],
    category: HabitEmojiCategories.nature,
  ),
  EmojiOption(
    emoji: '🍃',
    label: 'Aire libre',
    keywords: <String>[
      'aire libre',
      'outside',
      'fresh air',
      'nature',
      'leaf',
      'walk',
    ],
    category: HabitEmojiCategories.nature,
  ),
  EmojiOption(
    emoji: '🌻',
    label: 'Flores',
    keywords: <String>[
      'flores',
      'flower',
      'garden',
      'nature',
      'sunflower',
      'plant',
    ],
    category: HabitEmojiCategories.nature,
  ),
  EmojiOption(
    emoji: '🐾',
    label: 'Paseo',
    keywords: <String>[
      'paseo',
      'pet',
      'mascota',
      'walk',
      'nature',
      'outdoor',
    ],
    category: HabitEmojiCategories.nature,
  ),
  EmojiOption(
    emoji: '🌲',
    label: 'Bosque',
    keywords: <String>[
      'bosque',
      'forest',
      'nature',
      'hiking',
      'tree',
      'mountain',
    ],
    category: HabitEmojiCategories.nature,
  ),
  EmojiOption(
    emoji: '✨',
    label: 'Espiritualidad',
    keywords: <String>[
      'espiritualidad',
      'spirituality',
      'magic',
      'gratitud',
      'calma',
      'ritual',
    ],
    category: HabitEmojiCategories.spirituality,
  ),
  EmojiOption(
    emoji: '📿',
    label: 'Rezar',
    keywords: <String>[
      'rezar',
      'orar',
      'pray',
      'beads',
      'spirituality',
      'devocion',
    ],
    category: HabitEmojiCategories.spirituality,
  ),
  EmojiOption(
    emoji: '🤍',
    label: 'Paz',
    keywords: <String>[
      'paz',
      'peace',
      'calm',
      'quiet',
      'self compassion',
      'gentle',
    ],
    category: HabitEmojiCategories.spirituality,
  ),
  EmojiOption(
    emoji: '🪷',
    label: 'Loto',
    keywords: <String>[
      'loto',
      'lotus',
      'meditacion',
      'spirituality',
      'zen',
      'calma',
    ],
    category: HabitEmojiCategories.spirituality,
  ),
  EmojiOption(
    emoji: '☯️',
    label: 'Equilibrio',
    keywords: <String>[
      'equilibrio',
      'balance',
      'yin yang',
      'spirituality',
      'mindful',
      'harmony',
    ],
    category: HabitEmojiCategories.spirituality,
  ),
  EmojiOption(
    emoji: '🔮',
    label: 'Intuicion',
    keywords: <String>[
      'intuicion',
      'intuition',
      'reflection',
      'spirituality',
      'ritual',
      'vision',
    ],
    category: HabitEmojiCategories.spirituality,
  ),
  EmojiOption(
    emoji: '🎮',
    label: 'Videojuegos',
    keywords: <String>[
      'videojuegos',
      'gaming',
      'game',
      'ocio',
      'fun',
      'play',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '🎬',
    label: 'Ver pelicula',
    keywords: <String>[
      'pelicula',
      'cine',
      'movie',
      'film',
      'ocio',
      'watch',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '📺',
    label: 'Series',
    keywords: <String>[
      'series',
      'tv',
      'television',
      'watch',
      'ocio',
      'relax',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '🎲',
    label: 'Jugar',
    keywords: <String>[
      'jugar',
      'play',
      'game',
      'board game',
      'ocio',
      'fun',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '♟️',
    label: 'Ajedrez',
    keywords: <String>[
      'ajedrez',
      'chess',
      'strategy',
      'juego',
      'ocio',
      'think',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '🏖️',
    label: 'Playa',
    keywords: <String>[
      'playa',
      'beach',
      'vacaciones',
      'ocio',
      'sea',
      'relax',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '✈️',
    label: 'Viajar',
    keywords: <String>[
      'viajar',
      'travel',
      'trip',
      'flight',
      'ocio',
      'vacaciones',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '🍿',
    label: 'Snack',
    keywords: <String>[
      'snack',
      'palomitas',
      'movie night',
      'ocio',
      'comida',
      'fun',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '🎣',
    label: 'Pescar',
    keywords: <String>[
      'pescar',
      'fishing',
      'outdoor',
      'ocio',
      'nature',
      'relax',
    ],
    category: HabitEmojiCategories.leisure,
  ),
  EmojiOption(
    emoji: '⭐',
    label: 'Importante',
    keywords: <String>[
      'importante',
      'star',
      'favorite',
      'top',
      'highlight',
      'priority',
    ],
    category: HabitEmojiCategories.others,
  ),
  EmojiOption(
    emoji: '📍',
    label: 'Ubicacion',
    keywords: <String>[
      'ubicacion',
      'location',
      'place',
      'recordar',
      'marker',
      'track',
    ],
    category: HabitEmojiCategories.others,
  ),
  EmojiOption(
    emoji: '🧭',
    label: 'Direccion',
    keywords: <String>[
      'direccion',
      'compass',
      'orientacion',
      'goal',
      'path',
      'guide',
    ],
    category: HabitEmojiCategories.others,
  ),
  EmojiOption(
    emoji: '🏆',
    label: 'Logro',
    keywords: <String>[
      'logro',
      'win',
      'award',
      'achievement',
      'goal',
      'success',
    ],
    category: HabitEmojiCategories.others,
  ),
  EmojiOption(
    emoji: '🚀',
    label: 'Impulso',
    keywords: <String>[
      'impulso',
      'launch',
      'momentum',
      'motivation',
      'start',
      'boost',
    ],
    category: HabitEmojiCategories.others,
  ),
  EmojiOption(
    emoji: '💡',
    label: 'Idea',
    keywords: <String>[
      'idea',
      'thinking',
      'brainstorm',
      'creative',
      'insight',
      'lightbulb',
    ],
    category: HabitEmojiCategories.others,
  ),
  EmojiOption(
    emoji: '🔔',
    label: 'Recordatorio',
    keywords: <String>[
      'recordatorio',
      'reminder',
      'alert',
      'bell',
      'task',
      'todo',
    ],
    category: HabitEmojiCategories.others,
  ),
  EmojiOption(
    emoji: '🛠️',
    label: 'Construir',
    keywords: <String>[
      'construir',
      'build',
      'fix',
      'tools',
      'project',
      'work',
    ],
    category: HabitEmojiCategories.others,
  ),
];
