// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFW-cqNzWn39pJyt3Gz7_05VVVA0zPQE',
    appId: '1:514142796292:web:55fe6401a0cd52b5bcd351',
    messagingSenderId: '514142796292',
    projectId: 'rutio-app',
    authDomain: 'rutio-app.firebaseapp.com',
    storageBucket: 'rutio-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8xinQk8dczqlqbiPwYlnJsUqzqs3ICP8',
    appId: '1:514142796292:android:f113baaa248ed894bcd351',
    messagingSenderId: '514142796292',
    projectId: 'rutio-app',
    storageBucket: 'rutio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjMYRtoAXN4EEOrJNQqExmuBzMd4oK8MU',
    appId: '1:514142796292:ios:8c204ecb672a6ef1bcd351',
    messagingSenderId: '514142796292',
    projectId: 'rutio-app',
    storageBucket: 'rutio-app.firebasestorage.app',
    iosBundleId: 'com.rutio.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjMYRtoAXN4EEOrJNQqExmuBzMd4oK8MU',
    appId: '1:514142796292:ios:3633cc772b4afa87bcd351',
    messagingSenderId: '514142796292',
    projectId: 'rutio-app',
    storageBucket: 'rutio-app.firebasestorage.app',
    iosBundleId: 'com.example.habitCity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuFW-cqNzWn39pJyt3Gz7_05VVVA0zPQE',
    appId: '1:514142796292:web:b025d4ce1c84a195bcd351',
    messagingSenderId: '514142796292',
    projectId: 'rutio-app',
    authDomain: 'rutio-app.firebaseapp.com',
    storageBucket: 'rutio-app.firebasestorage.app',
  );
}
