begin;

-- Seed the active cosmetic catalog (wallpapers, habit cards and user cards).
-- Assets remain local; Supabase stores only commercial metadata and inventory state.

with seed_data (
  id,
  category,
  subtype,
  rarity,
  price_coins,
  is_consumable,
  is_stackable,
  max_quantity,
  equip_slot,
  asset_key,
  localization_key,
  is_active,
  sort_order,
  catalog_version
) as (
  values
    ('wallpaper_mist_blue', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_mist_blue.webp', 'shopCosmetic_wallpaper_mist_blue_title', true, 0, 1),
    ('wallpaper_rutio_beige', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_rutio_beige.webp', 'shopCosmetic_wallpaper_rutio_beige_title', true, 1, 1),
    ('wallpaper_off_white', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_off_white.webp', 'shopCosmetic_wallpaper_off_white_title', true, 2, 1),
    ('wallpaper_mellow_camel', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_mellow_camel.webp', 'shopCosmetic_wallpaper_mellow_camel_title', true, 3, 1),
    ('wallpaper_stone_gray', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_stone_gray.webp', 'shopCosmetic_wallpaper_stone_gray_title', true, 4, 1),
    ('wallpaper_dusty_lilac', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_dusty_lilac.webp', 'shopCosmetic_wallpaper_dusty_lilac_title', true, 5, 1),
    ('wallpaper_clay_rose', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_clay_rose.webp', 'shopCosmetic_wallpaper_clay_rose_title', true, 6, 1),
    ('wallpaper_soft_terracotta', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_soft_terracotta.webp', 'shopCosmetic_wallpaper_soft_terracotta_title', true, 7, 1),
    ('wallpaper_soft_sage', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_soft_sage.webp', 'shopCosmetic_wallpaper_soft_sage_title', true, 8, 1),
    ('wallpaper_cream_yellow', 'screen_background', 'background', 'common', 120, false, false, 1, 'screen_background', 'assets/shop/wallpapers/common/wallpaper_cream_yellow.webp', 'shopCosmetic_wallpaper_cream_yellow_title', true, 9, 1),
    ('habit_card_warm_beige', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_rutio_beige.webp', 'shopCosmetic_habit_card_warm_beige_title', true, 10, 1),
    ('habit_card_soft_camel', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_soft_camel.webp', 'shopCosmetic_habit_card_soft_camel_title', true, 11, 1),
    ('habit_card_sand_plain', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_off_white.webp', 'shopCosmetic_habit_card_sand_plain_title', true, 12, 1),
    ('habit_card_cream_light', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_cream_yellow.webp', 'shopCosmetic_habit_card_cream_light_title', true, 13, 1),
    ('habit_card_mist_blue', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_mist_blue.webp', 'shopCosmetic_habit_card_mist_blue_title', true, 14, 1),
    ('habit_card_stone_gray', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_stone_gray.webp', 'shopCosmetic_habit_card_stone_gray_title', true, 15, 1),
    ('habit_card_dusty_lilac', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_dusty_lilac.webp', 'shopCosmetic_habit_card_dusty_lilac_title', true, 16, 1),
    ('habit_card_clay_rose', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_clay_rose.webp', 'shopCosmetic_habit_card_clay_rose_title', true, 17, 1),
    ('habit_card_soft_terracotta', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_soft_terracotta.webp', 'shopCosmetic_habit_card_soft_terracotta_title', true, 18, 1),
    ('habit_card_soft_sage', 'habit_card_background', 'habitCard', 'common', 120, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/common/habit_card_soft_sage.webp', 'shopCosmetic_habit_card_soft_sage_title', true, 19, 1),
    ('wallpaper_jungle_sunrise', 'screen_background', 'background', 'rare', 250, false, false, 1, 'screen_background', 'assets/shop/wallpapers/rare/wallpaper_jungle_sunrise.webp', 'shopCosmetic_wallpaper_jungle_sunrise_title', true, 20, 1),
    ('habit_card_lilac_dawn', 'habit_card_background', 'habitCard', 'rare', 250, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/rare/habit_card_lilac_dawn.webp', 'shopCosmetic_habit_card_lilac_dawn_title', true, 21, 1),
    ('wallpaper_carnival_pastel', 'screen_background', 'background', 'rare', 250, false, false, 1, 'screen_background', 'assets/shop/wallpapers/rare/wallpaper_carnival_pastel.webp', 'shopCosmetic_wallpaper_carnival_pastel_title', true, 22, 1),
    ('habit_card_lavender_blue', 'habit_card_background', 'habitCard', 'rare', 250, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/rare/habit_card_lavender_blue.webp', 'shopCosmetic_habit_card_lavender_blue_title', true, 23, 1),
    ('wallpaper_strawberry_pastel', 'screen_background', 'background', 'rare', 250, false, false, 1, 'screen_background', 'assets/shop/wallpapers/rare/wallpaper_strawberry_pastel.webp', 'shopCosmetic_wallpaper_strawberry_pastel_title', true, 24, 1),
    ('habit_card_golden_camel', 'habit_card_background', 'habitCard', 'rare', 250, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/rare/habit_card_golden_camel.webp', 'shopCosmetic_habit_card_golden_camel_title', true, 25, 1),
    ('habit_card_sage_bloom', 'habit_card_background', 'habitCard', 'rare', 250, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/rare/habit_card_sage_bloom.webp', 'shopCosmetic_habit_card_sage_bloom_title', true, 26, 1),
    ('habit_card_dusty_rose', 'habit_card_background', 'habitCard', 'rare', 250, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/rare/habit_card_dusty_rose.webp', 'shopCosmetic_habit_card_dusty_rose_title', true, 27, 1),
    ('habit_card_pastel_sky', 'habit_card_background', 'habitCard', 'rare', 250, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/rare/habit_card_pastel_sky.webp', 'shopCosmetic_habit_card_pastel_sky_title', true, 28, 1),
    ('habit_card_soft_peach', 'habit_card_background', 'habitCard', 'rare', 250, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/rare/habit_card_soft_peach.webp', 'shopCosmetic_habit_card_soft_peach_title', true, 29, 1),
    ('habit_card_ocean_depth', 'habit_card_background', 'habitCard', 'epic', 550, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/epic/habit_card_ocean_depth.webp', 'shopCosmetic_habit_card_ocean_depth_title', true, 30, 1),
    ('habit_card_city_sunrise', 'habit_card_background', 'habitCard', 'epic', 550, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/epic/habit_card_city_sunrise.webp', 'shopCosmetic_habit_card_city_sunrise_title', true, 31, 1),
    ('habit_card_leopard', 'habit_card_background', 'habitCard', 'epic', 550, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/epic/habit_card_leopard.webp', 'shopCosmetic_habit_card_leopard_title', true, 32, 1),
    ('habit_card_full_moon', 'habit_card_background', 'habitCard', 'epic', 550, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/epic/habit_card_full_moon.webp', 'shopCosmetic_habit_card_full_moon_title', true, 33, 1),
    ('habit_card_golden_clouds', 'habit_card_background', 'habitCard', 'epic', 550, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/epic/habit_card_golden_clouds.webp', 'shopCosmetic_habit_card_golden_clouds_title', true, 34, 1),
    ('habit_card_zebra_minimal', 'habit_card_background', 'habitCard', 'epic', 550, false, false, 1, 'habit_card_background', 'assets/shop/habit_cards/epic/habit_card_zebra_minimal.webp', 'shopCosmetic_habit_card_zebra_minimal_title', true, 35, 1),
    ('wallpaper_starry_sky', 'screen_background', 'background', 'epic', 550, false, false, 1, 'screen_background', 'assets/shop/wallpapers/epic/wallpaper_starry_sky.webp', 'shopCosmetic_wallpaper_starry_sky_title', true, 36, 1),
    ('wallpaper_mint_abstract', 'screen_background', 'background', 'epic', 550, false, false, 1, 'screen_background', 'assets/shop/wallpapers/epic/wallpaper_mint_abstract.webp', 'shopCosmetic_wallpaper_mint_abstract_title', true, 37, 1),
    ('wallpaper_zebra_minimal', 'screen_background', 'background', 'epic', 550, false, false, 1, 'screen_background', 'assets/shop/wallpapers/epic/wallpaper_zebra_minimal.webp', 'shopCosmetic_wallpaper_zebra_minimal_title', true, 38, 1),
    ('wallpaper_wild_stripes', 'screen_background', 'background', 'epic', 550, false, false, 1, 'screen_background', 'assets/shop/wallpapers/epic/wallpaper_wild_stripes.webp', 'shopCosmetic_wallpaper_wild_stripes_title', true, 39, 1),
    ('wallpaper_cow_spots', 'screen_background', 'background', 'epic', 550, false, false, 1, 'screen_background', 'assets/shop/wallpapers/epic/wallpaper_cow_spots.webp', 'shopCosmetic_wallpaper_cow_spots_title', true, 40, 1),
    ('wallpaper_city_sunrise', 'screen_background', 'background', 'epic', 550, false, false, 1, 'screen_background', 'assets/shop/wallpapers/epic/wallpaper_city_sunrise.webp', 'shopCosmetic_wallpaper_city_sunrise_title', true, 41, 1),
    ('wallpaper_ocean_depth', 'screen_background', 'background', 'epic', 550, false, false, 1, 'screen_background', 'assets/shop/wallpapers/epic/wallpaper_ocean_depth.webp', 'shopCosmetic_wallpaper_ocean_depth_title', true, 42, 1),
    ('user_card_warm_beige', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_rutio_beige.webp', 'shopCosmetic_user_card_warm_beige_title', true, 44, 1),
    ('user_card_soft_camel', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_soft_camel.webp', 'shopCosmetic_user_card_soft_camel_title', true, 45, 1),
    ('user_card_sand_plain', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_off_white.webp', 'shopCosmetic_user_card_sand_plain_title', true, 46, 1),
    ('user_card_cream_light', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_cream_yellow.webp', 'shopCosmetic_user_card_cream_light_title', true, 47, 1),
    ('user_card_mist_blue', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_mist_blue.webp', 'shopCosmetic_user_card_mist_blue_title', true, 48, 1),
    ('user_card_stone_gray', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_stone_gray.webp', 'shopCosmetic_user_card_stone_gray_title', true, 49, 1),
    ('user_card_dusty_lilac', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_dusty_lilac.webp', 'shopCosmetic_user_card_dusty_lilac_title', true, 50, 1),
    ('user_card_clay_rose', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_clay_rose.webp', 'shopCosmetic_user_card_clay_rose_title', true, 51, 1),
    ('user_card_soft_terracotta', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_soft_terracotta.webp', 'shopCosmetic_user_card_soft_terracotta_title', true, 52, 1),
    ('user_card_soft_sage', 'user_card_background', 'userCard', 'common', 120, false, false, 1, 'user_card_background', 'assets/shop/user_cards/common/user_card_soft_sage.webp', 'shopCosmetic_user_card_soft_sage_title', true, 53, 1),
    ('user_card_lilac_dawn', 'user_card_background', 'userCard', 'rare', 250, false, false, 1, 'user_card_background', 'assets/shop/user_cards/rare/user_card_lilac_dawn.webp', 'shopCosmetic_user_card_lilac_dawn_title', true, 54, 1),
    ('user_card_dusty_rose', 'user_card_background', 'userCard', 'rare', 250, false, false, 1, 'user_card_background', 'assets/shop/user_cards/rare/user_card_dusty_rose.webp', 'shopCosmetic_user_card_dusty_rose_title', true, 55, 1),
    ('user_card_golden_camel', 'user_card_background', 'userCard', 'rare', 250, false, false, 1, 'user_card_background', 'assets/shop/user_cards/rare/user_card_golden_camel.webp', 'shopCosmetic_user_card_golden_camel_title', true, 56, 1),
    ('user_card_pastel_sky', 'user_card_background', 'userCard', 'rare', 250, false, false, 1, 'user_card_background', 'assets/shop/user_cards/rare/user_card_pastel_sky.webp', 'shopCosmetic_user_card_pastel_sky_title', true, 57, 1),
    ('user_card_soft_peach', 'user_card_background', 'userCard', 'rare', 250, false, false, 1, 'user_card_background', 'assets/shop/user_cards/rare/user_card_soft_peach.webp', 'shopCosmetic_user_card_soft_peach_title', true, 58, 1),
    ('user_card_ocean_depth', 'user_card_background', 'userCard', 'epic', 550, false, false, 1, 'user_card_background', 'assets/shop/user_cards/epic/user_card_ocean_depth.webp', 'shopCosmetic_user_card_ocean_depth_title', true, 59, 1),
    ('user_card_city_sunrise', 'user_card_background', 'userCard', 'epic', 550, false, false, 1, 'user_card_background', 'assets/shop/user_cards/epic/user_card_city_sunrise.webp', 'shopCosmetic_user_card_city_sunrise_title', true, 60, 1),
    ('user_card_full_moon', 'user_card_background', 'userCard', 'epic', 550, false, false, 1, 'user_card_background', 'assets/shop/user_cards/epic/user_card_full_moon.webp', 'shopCosmetic_user_card_full_moon_title', true, 61, 1)
)
insert into public.shop_items (
  id,
  category,
  subtype,
  rarity,
  price_coins,
  is_consumable,
  is_stackable,
  max_quantity,
  equip_slot,
  asset_key,
  localization_key,
  is_active,
  sort_order,
  catalog_version
)
select
  id,
  category,
  subtype,
  rarity,
  price_coins,
  is_consumable,
  is_stackable,
  max_quantity,
  equip_slot,
  asset_key,
  localization_key,
  is_active,
  sort_order,
  catalog_version
from seed_data
order by category, rarity, sort_order, id
on conflict (id) do update set
  category = excluded.category,
  subtype = excluded.subtype,
  rarity = excluded.rarity,
  price_coins = excluded.price_coins,
  is_consumable = excluded.is_consumable,
  is_stackable = excluded.is_stackable,
  max_quantity = excluded.max_quantity,
  equip_slot = excluded.equip_slot,
  asset_key = excluded.asset_key,
  localization_key = excluded.localization_key,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  catalog_version = excluded.catalog_version,
  updated_at = now();

commit;
